### ISSUE TITLE
Sparsity benchmarks

### ISSUE THREAD

**Issue by qeternity** [neuralmagic/nm-vllm#114]
Interesting project. I came across it looking at Marlin models on HF.

Do you have any benchmarks (performance and perplexity) for sparse models? I see one graph in the readme but it's not clear if that is token latency or throughput. And I'd love to see a perplexity curve at various levels of sparsity.

More than happy to do these tests myself but if you have these handy, they are definitely worth adding to the readme for passersby like me who are constantly looking to shave off a few ms for latency sensitive applications.

**Comment by jeanniefinks** [comment]
Hi @qeternity 
As some time has passed with no further comments, I am going to close out this thread. Feel free to re-open this if you want to continue the discussion. 

If you not have starred our NM repos and you feel inclined, we appreciate the support! Thanks ⭐ 
Regards, 
Jeannie / Neural Magic
