### ISSUE TITLE
[Doc]: Support Mixtral?

### ISSUE THREAD

**Issue by Xu-Chen** [neuralmagic/nm-vllm#139]
### 📚 The doc issue

How effective is the acceleration of the mixtral model?

**Comment by robertgshaw2-neuralmagic** [comment]
@Xu-Chen 

We can run fp16 mixtral, same as vllm upstream.

We are currently working on expanding 4bit marlin to support fused MoE kernel. 

@ElizaWszola and @alexm-nm are working on this currently

**Comment by Xu-Chen** [comment]
> @Xu-Chen
> 
> We can run fp16 mixtral, same as vllm upstream.
> 
> We are currently working on extending 4bit marlin to support fused MoE needed for Mixtral
> 
> @ElizaWszola and @alexm-nm are working on this currently

Thank you, you are doing a great job

**Comment by Xu-Chen** [comment]
As we can see, there are a lot of MOE models like DBRX, QwenMOE, so supporting moe models with marlin is pretty impressive. Thank you for your great job.
