### ISSUE TITLE
[Doc]: Whether it's possible to apply both sparse and quantization simultaneously?

### ISSUE THREAD

**Issue by wangzhenyu32** [neuralmagic/nm-vllm#176]
### 📚 The doc issue

I have read the examples in both examples and examples-neuralmagic directories. I found examples demonstrating the use of quantization techniques as well as examples demonstrating the use of sparse techniques. However, I haven't found any examples demonstrating the simultaneous use of both sparse and quantization techniques. Can you confirm whether it's possible to apply both of these techniques simultaneously during deployment using the nm-vllm library?

**Comment by robertgshaw2-neuralmagic** [comment]
@wangzhenyu32 Thanks for your interest.

We are in fact actively working on sparse-quantized kernels and hope to push them out soon. We supported these in our CPU runtime (DeepSparse) and will bring them to vLLM as well.
