### ISSUE TITLE
[Doc]: quantize.py script for making Marlin quants

### ISSUE THREAD

**Issue by RonanKMcGovern** [neuralmagic/nm-vllm#199]
### 📚 The doc issue

Since marlin is supported, can a simple quantization script be provided?

### Suggest a potential alternative/fix

or point to a repo with such a script.

**Comment by robertgshaw2-neuralmagic** [comment]
https://github.com/neuralmagic/nm-vllm/tree/main/examples-neuralmagic/marlin_quantization_and_deploy

**Comment by robertgshaw2-neuralmagic** [comment]
We are working on a new version of this through [SparseML](https://github.com/neuralmagic/sparseml), but the example above is your best bet for now

**Comment by RonanKMcGovern** [comment]
Thanks, appreciate that.

I suppose the GPTQ method though won't be great on quality though, at least
compared to AWQ or NF4?
