### ISSUE TITLE
[Feature]: New model request llama-3 70b

### ISSUE THREAD

**Issue by souvik3333** [neuralmagic/nm-vllm#206]
### 🚀 The feature, motivation and pitch

There are [few](https://huggingface.co/MaziyarPanahi/Meta-Llama-3-70B-Instruct-GPTQ) llama 3 70b GPTQ models available. Can we use that directly?

**Comment by mgoin** [comment]
Yes please try them! I have tested these GPTQ-quantized Marlin models with nm-vllm

https://huggingface.co/mgoin/Meta-Llama-3-8B-Instruct-Marlin
https://huggingface.co/mgoin/Meta-Llama-3-70B-Instruct-Marlin

**Comment by abpani** [comment]
For me it is not working.
says unknown layout.
can you please help
