### ISSUE TITLE
[Bug]: CUDA error: an illegal instruction was encountered

### ISSUE THREAD

**Issue by aliustunelin** [neuralmagic/nm-vllm#226]
### File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 783, in synchronize
    return torch._C._cuda_synchronize()

### 🐛 Describe the bug

Hello,
I am installing the mgoin/Meta-Llama-3-70B-Instruct-Marlin model in the H100 GPU.

I am using nm-vllm 0.2.0 version as LLM engine.
Actually my problem

File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 783, in synchronize
     return torch._C._cuda_synchronize()

It appears in the section: There is an incompatibility between CUDA Torch and VLLM.

```
My error message:
RuntimeError: CUDA error: an illegal instruction was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Library information I use:
torch 2.1.2
nm-vllm 0.2.0
filelock 3.14.0

I did not encounter any problems with the A100 processor, but I am getting the error code in the H100 GPU.

When I change package versions, I get other errors.

The model comes from huggingface.

I keep the model in cache so that huggingface does not change my cuda and pytorch versions, and I change my package versions this way. I have a special environment in this regard.

Have you ever received this error in H100?

**Comment by mgoin** [comment]
Hey @aliustunelin we already resolved this issue with Marlin during this issue https://github.com/neuralmagic/nm-vllm/issues/187. Our current recommendation is to build from main - we will have a new release shortly!
