### ISSUE TITLE
[Doc]: Are we capable of automatically converting GGUF models into Marlin, similar to our support for GPTQ?

### ISSUE THREAD

**Issue by ericzhou571** [neuralmagic/nm-vllm#235]
### 📚 The doc issue

Marlin quantization inference efficiency is truly remarkable, significantly outperforming AWQ or GPTQ in harnessing the acceleration of tensor parallelism. Moreover, its concurrent performance is also far superior to that of AWQ or GPTQ. 
We have an excellent feature that automatically converts GPTQ to Marlin during deployment. I wonder if such a feature could be applied to the quantization mode of GGUF?

**Comment by robertgshaw2-neuralmagic** [comment]
We do not currently support GGUF models via Marlin

**Comment by robertgshaw2-neuralmagic** [comment]
Do you know of  away to convert a GGUF model to an AutoGPTQ checkpoint?

**Comment by ericzhou571** [comment]
> Do you know of a way to convert a GGUF model to an AutoGPTQ checkpoint?

Thanks a lot for reply!  I'm sorry that, I have no idea either. 
I asked this question because Yi just released their 1.5 version, but they officially only released a gguf quantized version. 
I believe making a GPTQ quantization from the bf16 version would save a significant amount of time and might have less performance loss than some how convert from gguf version to gptq version, since they also release a bf16 version. close the issue.

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks Eric! Please let me know if there is anything else we can do for you!
