### ISSUE TITLE
[Usage]:  Any guide for generating a 2:4 sparse int4 weight model?

### ISSUE THREAD

**Issue by AniZpZ** [neuralmagic/nm-vllm#254]
Interesting work! 
I am planning to test our model using 2:4 sparsity combined with W4A16 quantization. However, I have not found any documentations or scripts for generating the model weights. Could you please provide some guidance?

**Comment by mgoin** [comment]
Hi @AniZpZ thanks for the early interest! We will be releasing model weights and documentation for sparse fine-tuning them in the coming weeks.
