### ISSUE TITLE
[Usage]: Could we generate model for marlin2:4 kernel with sparsegpt?

### ISSUE THREAD

**Issue by ericzhou571** [neuralmagic/nm-vllm#268]
Great work!
We are attempting to develop a model with 2:4 sparsity and 4-bit quantization using the assistance of [sparsegpt](https://github.com/IST-DASLab/sparsegpt). 
@mgoin, could you please confirm if this is the correct approach to create a compatible model for our recently updated marlin 2:4 kernel?
Below is the code snippet we are using from `sparsegpt`:
```python
python llama.py LLAMA_HF_WEIGHTS_LOCATION c4 --prunen 2 --prunem 4 --wbits 4
```

**Comment by ericzhou571** [comment]
We find a detail guide in huggingface, close the issue https://huggingface.co/neuralmagic/OpenHermes-2.5-Mistral-7B-pruned2.4

**Comment by mgoin** [comment]
Hey @ericzhou571 that is right for the 2:4 sparsity of the model, but not for the quantization. We do the quantization through a fork of AutoGPTQ (currently here https://github.com/neuralmagic/nm-AutoGPTQ/pull/1) but we are working on official flows that we will publish in a blog in a few weeks!

**Comment by yzlnew** [comment]
@mgoin Hi, can I perform the whole workflow using sparseml? Notice there's an [example](https://github.com/neuralmagic/sparseml/tree/main/examples/llama7b_sparse_quantized). I tried the recipe on the Qwen model, was able to inference on the sparse ckpt using nm-vllm but no improvement observed. Also failed to inference on the sparse-quant ckpt using vllm or nm-vllm.

**Comment by mgoin** [comment]
Hi @yzlnew thanks for trying it early but it won't work yet. It will run but won’t take advantage of the sparsity structure. We will provide guides for this once it is ready!

**Comment by yzlnew** [comment]
This issue is completed, any link to the marlin2:4 training docs?
