### ISSUE TITLE
[Usage]:  Do you have any plans to support sparse fp8 kernel and support on rocm?

### ISSUE THREAD

**Issue by DehuaTang** [neuralmagic/nm-vllm#382]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

Great job !   Do you have any plans to support sparse fp8 kernel and support it on rocm?

**Comment by mgoin** [comment]
It isn't a plan at the moment but I could see us implementing it in the future if there is a use-case
