### ISSUE TITLE
[Misc]: Is Magic Wand SparseBitmaskStorageFormat open sourced? 

### ISSUE THREAD

**Issue by dhjoo98** [neuralmagic/nm-vllm#402]
### Anything you want to discuss about vllm.

Hello, I am interested in how the bitmask representation is processed in GPU. 
By scanning the nm-vllm code, SparseBitmaskStorageFormat seems to be from a pip package called nm-magic-wand. 

I was wondering if the source code that pip package is not open sourced.

**Comment by mgoin** [comment]
Hi @dhjoo98 nm-magic-wand is closed source.
